### ISSUE TITLE
HCJ-Editor-Webseite

### ISSUE THREAD

**Issue by Johannes97** [FG-Team/HCJ-Website-Builder#35]
Hey Leute, 
habe das Issue hier erstellt, um euch zu fragen, was ihr von einer Internetseite für unseren HCJ-Editor haltet, damit dieser für alle frei zugänglich ist :). Allerdings halte ich es erstmal für sinnvoll, den Editor fertig zu machen, bevor wir uns um eine Webseite kümmern würden. 
Würde gerne eure Meinungen dazu hören.
(Hoffe es war richtig einen Issue für dieses Thema zu erstellen.)
LG Johannes.

**Comment by grhcj** [comment]
Ich schließe das mal, da keine (grundsätzlichen) Einsprüche gegen die Verwendung von github pages geäußert wurden. Selbst Johannes' Vorschlag lässt sich damit realisieren.
