### ISSUE TITLE
Page "Set cell content"

### ISSUE THREAD

**Issue by grhcj** [FG-Team/HCJ-Website-Builder#42]
Diese Seite bietet die Möglichkeit, den Inhalt einer Zelle in einer Tabelle zu bearbeiten.

**Comment by grhcj** [comment]
Rohbau ist fertig.
Ich suche jemanden, der den presenter fertigstellt (ihr müsst Euch die Methoden eventuell selbst überlegen, schaut Euch mal den Presenter im "Page_Create_table"-branch an.

**Comment by Dargmuesli** [comment]
Ich bin gerade nicht zu Hause, wird in den nächsten Tagen schwierig..
Am 02.01.2015 18:59 schrieb Lukas Mentel <notifications@github.com>:Rohbau ist fertig.
Ich suche jemanden, der den presenter fertigstellt (ihr müsst Euch die Methoden eventuell selbst überlegen, schaut Euch mal den Presenter im "Page_Create_table"-branch an.
